### ISSUE TITLE
Make things that shouldn't be selectable unselectable

### ISSUE THREAD

**Issue by honglio** [honglio/niukj#65]
It's really annoying when a user trying to interact with an element causes the element, or the text within it, to be selected instead. Adding user-select: none to everything, except for the things that a user would genuinely want to copy paste can cut way down on these interactions being accidentally triggered.

Adding -webkit-touch-callout: none; to an element prevents a tap and hold from opening a context menu on the link or image.

```css
user-select: none;
-{prefix}-user-select: none;
-webkit-touch-callout: none;
```
On Android, to stop these menu's from showing up, you can do:

```javascript
if(navigator.userAgent.match(/Android/i))
  noContextMenu.addEventListener('contextmenu', function (e) { e.preventDefault() })
```
#27
