### ISSUE TITLE
Get rid of ugly grey tap highlight.

### ISSUE THREAD

**Issue by honglio** [honglio/niukj#66]
By default, mobile web browsers display a tap highlight, so that users get feedback when they tap something. Unfortunately it looks awful and is a dead giveaway that your app isn't native.

The really easy solution is to add this to your css. You NEVER want the default highlight.
```css
* {
  -webkit-tap-highlight-color: rgba(0,0,0,0);
}
```
#27
